### ISSUE TITLE
Dev Note

### ISSUE THREAD

**Issue by hackycy** [hackycy/blog-source#6]
IOS App图标格式：
通知图标所需：40*40 和 60*60
设置图标所需：58*58 和 87*87
Spotlight图标所需：80*80 和 120*120
App启动图标所需：120*120 和 180*180
AppStore图标为1024*1024

Android App图标格式：
ldpi文件夹图标需变更为92*92
mdpi文件夹图标需变更为144*144
hdpi文件夹图标需变更为192*192
xhdpi文件夹图标需要变更为256*256
xxhdpi文件夹图标需要变更为384*384
xxxhdpi文件夹图标需要变更为512*512

./gradlew processDebugManifest -stacktrace

**Comment by hackycy** [comment]
Jenkins脚本

DeployCode="/home/deploy"
DstDir="/www/wwwroot/test.si-yee.com/"
PRONAME="JenkinsDemo"
COMMITID="$(git rev-parse --short HEAD)"
PKGNAME="${PRONAME}-${COMMITID}"
cp -rf ${WORKSPACE} ${DeployCode}/ && cd ${DeployCode} && mv ${PRONAME} ${PKGNAME}
cd ${DeployCode}/${PKGNAME} && rm -rf .git
cd ${DeployCode} && tar zcf ${PKGNAME}.tar.gz ${PKGNAME} && cp ${PKGNAME}.tar.gz ${DstDir}
cd ${DstDir} && tar -xvf ${PKGNAME}.tar.gz -C ${DstDir} && rm -rf ${PKGNAME}.tar.gz
cd ${DstDir} && cp -R ${PKGNAME}/* ${DstDir} && rm -rf ${PKGNAME}

**Comment by hackycy** [comment]
空包签名：

jarsigner -verbose -keystore keystore文件路径 -signedjar 签名后的文件apk 要签名的原apk keystore的别名

**Comment by hackycy** [comment]
小米推送运营平台文档：
https://dev.mi.com/console/doc/detail?pId=1551


小米推送开发文档：
https://dev.mi.com/console/doc/detail?pId=41#_4_1


OPPO推送运营平台文档：
https://open.oppomobile.com/wiki/doc#id=10198


OPPO推送开发文档：
https://open.oppomobile.com/wiki/doc#id=10704


Vivo推送运营平台文档：
https://dev.vivo.com.cn/documentCenter/doc/151


Vivo推送开发文档：
https://dev.vivo.com.cn/documentCenter/doc/233


华为推送运营平台文档：
https://developer.huawei.com/consumer/cn/doc/development/HMS-Guides/push-console

华为推送开发文档：
https://developer.huawei.com/consumer/cn/doc/development/HMS-Guides/push-basic-capability

**Comment by hackycy** [comment]
iOS 黑马微博项目笔记：

![image](https://user-images.githubusercontent.com/26972260/84849251-7b10e600-b087-11ea-8c59-b5d0a41f0d89.png)

![image](https://user-images.githubusercontent.com/26972260/84849259-7fd59a00-b087-11ea-93de-8f33301d77d4.png)

![image](https://user-images.githubusercontent.com/26972260/84849269-83692100-b087-11ea-9112-6e67a63d9f4a.png)

![image](https://user-images.githubusercontent.com/26972260/84849274-86641180-b087-11ea-8b8d-c84afbe0d493.png)

![image](https://user-images.githubusercontent.com/26972260/84849281-88c66b80-b087-11ea-82d0-7c9fbefabe50.png)

![image](https://user-images.githubusercontent.com/26972260/84849284-8bc15c00-b087-11ea-806c-00883f61f6db.png)

![image](https://user-images.githubusercontent.com/26972260/84849289-8e23b600-b087-11ea-8891-1ec5e49c8951.png)

![image](https://user-images.githubusercontent.com/26972260/84849292-90861000-b087-11ea-8934-a8d40c121115.png)

![image](https://user-images.githubusercontent.com/26972260/84849300-92e86a00-b087-11ea-81a2-9878724c4938.png)

![image](https://user-images.githubusercontent.com/26972260/84849306-95e35a80-b087-11ea-8c3b-468a16406e18.png)

![image](https://user-images.githubusercontent.com/26972260/84849312-9845b480-b087-11ea-8f93-4d64ab5bfdc9.png)

![image](https://user-images.githubusercontent.com/26972260/84849318-9aa80e80-b087-11ea-9fc8-4d25f1a69004.png)

![image](https://user-images.githubusercontent.com/26972260/84849326-9d0a6880-b087-11ea-9c2b-f898c7e56404.png)

![image](https://user-images.githubusercontent.com/26972260/84849331-9f6cc280-b087-11ea-9e2a-a3c61b1d7d88.png)

![image](https://user-images.githubusercontent.com/26972260/84849333-a1cf1c80-b087-11ea-811b-4480427c2944.png)

![image](https://user-images.githubusercontent.com/26972260/84849335-a4ca0d00-b087-11ea-92cd-27bf8fa03fa4.png)

![image](https://user-images.githubusercontent.com/26972260/84849344-a72c6700-b087-11ea-907c-385747d86002.png)

![image](https://user-images.githubusercontent.com/26972260/84849350-a8f62a80-b087-11ea-9930-f0bb21665ac0.png)

![image](https://user-images.githubusercontent.com/26972260/84849360-abf11b00-b087-11ea-9c05-6c9b9298deea.png)

![image](https://user-images.githubusercontent.com/26972260/84849367-ae537500-b087-11ea-9937-35341c815d1b.png)

![image](https://user-images.githubusercontent.com/26972260/84849373-b0b5cf00-b087-11ea-9697-6253aff19d86.png)

![image](https://user-images.githubusercontent.com/26972260/84849378-b3182900-b087-11ea-8004-573fd2e3234d.png)

![image](https://user-images.githubusercontent.com/26972260/84849383-b4e1ec80-b087-11ea-8c5f-cf4f0ce606d7.png)

![image](https://user-images.githubusercontent.com/26972260/84849385-b6abb000-b087-11ea-81b0-a0147f4299b6.png)

![image](https://user-images.githubusercontent.com/26972260/84849389-b90e0a00-b087-11ea-9d65-50848f8ae125.png)

![image](https://user-images.githubusercontent.com/26972260/84849392-bc08fa80-b087-11ea-93c7-48a8a1d770be.png)

![image](https://user-images.githubusercontent.com/26972260/84849396-bf03eb00-b087-11ea-9777-d1911ed64575.png)

**Comment by hackycy** [comment]
![image](https://user-images.githubusercontent.com/26972260/85492367-a22b6280-b607-11ea-8336-090e17770259.png)

**Comment by hackycy** [comment]
iOS 13 夜间模式适配

https://www.jianshu.com/p/e6616e44cf60

**Comment by hackycy** [comment]
Github SSH Action

``` yml
name: CI

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: denolib/setup-deno@v1
        with:
          deno-version: "v0.38.0"
      - name: build web
        run: |
          ./build.sh
      - name: Build Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS registry.cn-hongkong.aliyuncs.com
          docker build ./ -t registry.cn-hongkong.aliyuncs.com/denocn/denocn-website
          docker push registry.cn-hongkong.aliyuncs.com/denocn/denocn-website
  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: ${{ secrets.DEPLOY_SCRIPT }}
```

**Comment by hackycy** [comment]
![image](https://user-images.githubusercontent.com/26972260/90487625-4e537a80-e16d-11ea-9261-da42fe02f59f.png)

**Comment by hackycy** [comment]
github action schedule

``` yaml
name: build

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Run deno
        run: |
          git config --local user.email "dmdefine6@gmail.com"
          git config --local user.name "typeofNaN"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          deno run --unstable --allow-net --allow-read --allow-write --importmap=import_map.json mod.ts
          git add .
          git commit -m "get data by github actions"
          git push
```
